name: build
on:
  workflow_dispatch:
  push:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0

      - name: Configure CMake
        run: cmake . -B build

      - name: Build targets
        run: cmake --build build
