name: build
on:
  workflow_dispatch:
  push:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2.5.0
        with:
          fetch-depth: 0

      - name: Configure CMake
        run: cmake . -B build

      - name: Build targets
        run: cmake --build build

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2.5.0
        with:
          fetch-depth: 0

      - name: Install cmake-format
        run: pip3 install cmake-format

      - name: Configure CMake
        run: cmake . -B build -DBUILD_TESTING=ON -DCMAKE_CXX_FLAGS='-Werror'

      - name: Check for code formatting
        run: |
          cmake --build build --target format
          cmake --build build --target check-format

      - name: Build targets
        run: cmake --build build

      - name: Run tests
        run: ctest --test-dir build --verbose

      - name: Install gcovr
        run: pip3 install gcovr

      - name: Test for code coverage
        run: gcovr -e 'build/*' --fail-under-line 80

