name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  build-release:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Configure project
        uses: threeal/cmake-action@v1.3.0

      - name: Build project
        run: cmake --build build

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Configure project
        uses: threeal/cmake-action@v1.3.0
        with:
          options: BUILD_TESTING=ON

      - name: Build Project
        run: cmake --build build

      - name: Test Project
        run: ctest --test-dir build --output-on-failure --no-tests=error

      - name: Check test coverage
        uses: threeal/gcovr-action@v1.0.0
        with:
          excludes: build/*
          fail-under-line: 80

  check-formatting:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Install cmake-format
        run: pip3 install cmake-format

      - name: Configure CMake
        run: cmake . -B build

      - name: Check code formatting
        run: |
          cmake --build build --target format
          cmake --build build --target check-format
