name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  build-release:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Configure project
        uses: threeal/cmake-action@v1.3.0

      - name: Build project
        run: cmake --build build

  build-testing:
    name: Build Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install cmake-format
        run: pip3 install cmake-format

      - name: Configure project
        uses: threeal/cmake-action@v1.3.0
        with:
          options: BUILD_TESTING=ON

      - name: Check formatting
        run: |
          cmake --build build --target format
          git diff --exit-code HEAD

      - name: Build Project
        run: cmake --build build

      - name: Test Project
        run: ctest --test-dir build --output-on-failure --no-tests=error

      - name: Check coverage
        uses: threeal/gcovr-action@v1.0.0
        with:
          excludes: build/*
          fail-under-line: 80
